/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applic_trafic;

import ProtocoleTRAMAP.Client;
import ProtocoleTRAMAP.InputLorry;
import ProtocoleTRAMAP.ReponseTRAMAP;
import ProtocoleTRAMAP.RequeteTRAMAP;
import ProtocoleTRAMAP.User;
import java.awt.Color;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import utils.GetPropertyValues;

/**
 *
 * @author david
 */
public class FenAppMain extends javax.swing.JFrame {
    private InputLorry il;
    private User user;
    private ArrayList<Integer> list;
    private DefaultListModel dlm;
    private String host;
    private int port;

    /**
     * Creates new form FenAppMain2
     */
    public FenAppMain() {
        initComponents();
        bEnvoyer.setEnabled(false);
        labelAnnonce.setForeground(Color.red);
        
        DialLogin dl = new DialLogin(this, true);
        dl.setVisible(true);
        user = dl.getUser();
        tfSoc.setEnabled(false);
        host = GetPropertyValues.getPropValues("ip");
        port = Integer.parseInt(GetPropertyValues.getPropValues("portServeurTrafic"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bVerifier = new javax.swing.JButton();
        bEnvoyer = new javax.swing.JButton();
        tfNumR = new javax.swing.JTextField();
        labelAnnonce = new javax.swing.JLabel();
        labelContainer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelEmplacement = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelImma = new javax.swing.JLabel();
        jLabelIdContainer = new javax.swing.JLabel();
        jLabelIdEmp = new javax.swing.JLabel();
        jLabelXY = new javax.swing.JLabel();
        jTextFieldIdContainer = new javax.swing.JTextField();
        jTextFieldImma1 = new javax.swing.JTextField();
        bDemander = new javax.swing.JButton();
        jLabelAnnonceIWR = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContainers = new javax.swing.JList();
        tfDateDeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDateFin = new javax.swing.JTextField();
        jButtonAfficher = new javax.swing.JButton();
        tfDest = new javax.swing.JTextField();
        tfSoc = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabelAnnoncelist = new javax.swing.JLabel();
        bDeco = new javax.swing.JButton();
        lDeco = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N° Réservation :");

        jLabel2.setText("Id Container :");

        bVerifier.setText("Vérifier");
        bVerifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerifierActionPerformed(evt);
            }
        });

        bEnvoyer.setText("Envoyer");
        bEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnvoyerActionPerformed(evt);
            }
        });

        jLabel3.setText("Emplacement :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelAnnonce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bEnvoyer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNumR, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bVerifier))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmplacement)
                                    .addComponent(labelContainer))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bVerifier)
                    .addComponent(tfNumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelContainer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelEmplacement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEnvoyer)
                    .addComponent(labelAnnonce))
                .addContainerGap())
        );

        jTabbedPane1.addTab("InputLorry", jPanel1);

        jLabelImma.setText("Immatriculation : ");

        jLabelIdContainer.setText("Id container : ");

        jLabelIdEmp.setText("Emplacement : ");

        bDemander.setText("Demander place");
        bDemander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDemanderActionPerformed(evt);
            }
        });

        jLabelAnnonceIWR.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAnnonceIWR)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelIdEmp)
                            .addComponent(jLabelImma)
                            .addComponent(jLabelIdContainer))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabelXY))
                            .addComponent(jTextFieldImma1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDemander)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImma)
                    .addComponent(jTextFieldImma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdContainer)
                    .addComponent(jTextFieldIdContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdEmp)
                    .addComponent(jLabelXY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDemander)
                    .addComponent(jLabelAnnonceIWR))
                .addContainerGap())
        );

        jTabbedPane1.addTab("InputLorryWithoutResa", jPanel3);

        jScrollPane1.setViewportView(jListContainers);

        jLabel4.setText("Date debut : ");

        jLabel5.setText("Date fin : ");

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Id societe");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Destination");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabelAnnoncelist.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfDest, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(tfSoc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                .addComponent(jButtonAfficher))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAnnoncelist)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tfDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(tfDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(tfSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAfficher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelAnnoncelist)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Liste mouvement", jPanel4);

        bDeco.setText("Deconnexion");
        bDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(bDeco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lDeco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDeco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnvoyerActionPerformed
        System.out.println(il.toString());

        Client cli = new Client();
        try
        {
            cli.open(host, port);
            System.out.println("Client connecté : " + cli.getCliSock().getInetAddress().toString());
        }
        catch (UnknownHostException e)
        { System.err.println("Erreur ! Host non trouvé [" + e + "]"); }
        catch (IOException e)
        { System.err.println("Erreur ! Pas de connexion ? [" + e + "]"); }

        RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.INPUT_LORRY, il);

        try {
            cli.sendRequest(req);
        } catch (IOException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        //---->
        System.out.println("Input Lorry envoyé");

        try {
            ReponseTRAMAP rep = null;
            rep = cli.getResponse();

            if(rep.getCode().equals(ReponseTRAMAP.IL_OK)){
                labelAnnonce.setText("Input Lorry effectué avec succès !");
            }
            else{
                labelAnnonce.setText("Erreur lors de l'input lorry, veuillez recommencer");
            }

        } catch (IOException ex) {
            Logger.getLogger(DialLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bEnvoyerActionPerformed

    private void bVerifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerifierActionPerformed
        Client cli = new Client();
        try
        {
            cli.open(host, port);
            System.out.println("Client connecté : " + cli.getCliSock().getInetAddress().toString());
        }
        catch (UnknownHostException e)
        { System.err.println("Erreur ! Host non trouvé [" + e + "]"); }
        catch (IOException e)
        { System.err.println("Erreur ! Pas de connexion ? [" + e + "]"); }

        Boolean booleanVerif = false;
        ReponseTRAMAP rep = null;

        if(tfNumR.getText().equals(""))
        {
            labelAnnonce.setText("Numéro de reservation vide!");
        }
        else
        {
            RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.VERIF_NUM_RESA, tfNumR.getText());

            try {
                cli.sendRequest(req);
            } catch (IOException ex) {
                Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            //---->
            System.out.println("Num resa envoyé");
            //<----

            try {
                rep = cli.getResponse();

                if(rep.getCode().equals(ReponseTRAMAP.SEARCH_RESA_OK)){
                    booleanVerif = true;
                }
                else{
                    booleanVerif = false;
                }
            } catch (IOException ex) {
                Logger.getLogger(DialLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if(booleanVerif)
        {
            il = new InputLorry(tfNumR.getText(), rep.getContId(), rep.getX(), rep.getY());
            bVerifier.setEnabled(false);
            tfNumR.setEditable(false);
            if(rep != null){
                labelContainer.setText(Integer.toString(rep.getContId()));
                labelEmplacement.setText(Integer.toString(rep.getX()) + ";" + Integer.toString(rep.getY()));
            }
            bEnvoyer.setEnabled(true);
        }
        else
            labelAnnonce.setText("Numero de reservation inconnu");

        // Il peut y avoir une erreur maintenant si le container n'est PAS dans une réservation, on fera ça après
    }//GEN-LAST:event_bVerifierActionPerformed

    private void bDemanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDemanderActionPerformed
        Client cli = new Client();
        try
        {
            cli.open(host, port);
            System.out.println("Client connecté : " + cli.getCliSock().getInetAddress().toString());
        }
        catch (UnknownHostException e)
        { System.err.println("Erreur ! Host non trouvé [" + e + "]"); }
        catch (IOException e)
        { System.err.println("Erreur ! Pas de connexion ? [" + e + "]"); }
        
        ReponseTRAMAP rep = null;
        Boolean booleanVerif = false;
        
        if(jTextFieldImma1.getText().equals("")||jTextFieldIdContainer.getText().equals(""))
        {
            jLabelAnnonceIWR.setText("Les 2 champs doivent etre renseignées");
        }
        else
        {
            jLabelAnnonceIWR.setText("");
            RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.INPUT_LORRY_WITHOUT_RESA, jTextFieldImma1.getText(), jTextFieldIdContainer.getText());

            try {
                cli.sendRequest(req);
            } catch (IOException ex) {
                Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            //---->
            System.out.println("InputLorryWithoutResa envoyé");
            //<----
            try {
                rep = cli.getResponse();

                if(rep.getCode().equals(ReponseTRAMAP.ILWR_OK)){
                    jLabelXY.setText(rep.getPlace());
                    jLabelAnnonceIWR.setText("Input Lorry Without Reservation effectué avec succès !");
                    
                }
                else{
                    jLabelAnnonceIWR.setText("Erreur lors de l'input lorry Without Reservation, veuillez recommencer");
                }
                
            } catch (IOException ex) {
                Logger.getLogger(DialLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bDemanderActionPerformed

    private void bDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecoActionPerformed
        Client cli = new Client();
        try
        {
            cli.open(host, port);
            System.out.println("Client connecté : " + cli.getCliSock().getInetAddress().toString());
        }
        catch (UnknownHostException e)
        { System.err.println("Erreur ! Host non trouvé [" + e + "]"); }
        catch (IOException e)
        { System.err.println("Erreur ! Pas de connexion ? [" + e + "]"); }

        RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.LOGOUT, user);

        try {
            cli.sendRequest(req);
        } catch (IOException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        //---->

        try {
            ReponseTRAMAP rep = null;
            rep = cli.getResponse();

            if(rep.getCode().equals(ReponseTRAMAP.LOGOUT_OK)){
                System.exit(1);
            }
            else{
                lDeco.setText("Déconnexion impossible!");
            }

        } catch (IOException ex) {
            Logger.getLogger(DialLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bDecoActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        tfDest.setEnabled(false);
        tfSoc.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        tfSoc.setEnabled(false);
        tfDest.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        dlm = new DefaultListModel();
        
        Client cli = new Client();
        try
        {
            cli.open(host, port);
            System.out.println("Client connecté : " + cli.getCliSock().getInetAddress().toString());
        }
        catch (UnknownHostException e)
        { System.err.println("Erreur ! Host non trouvé [" + e + "]"); }
        catch (IOException e)
        { System.err.println("Erreur ! Pas de connexion ? [" + e + "]"); }
        
        Boolean booleanVerif = false;
        RequeteTRAMAP req = null;
        if(tfDateDeb.getText().equals("") || tfDateFin.getText().equals(""))
        {
            jLabelAnnoncelist.setText("Il faut remplir les champs");
        }
        else
        {
            System.out.println("Dest: " + tfDest.getText() + "Soc: " + tfSoc.getText());
            if(jRadioButton1.isSelected())
            {
                if(tfDest.getText().equals(""))
                    jLabelAnnoncelist.setText("Il faut remplir les champs");
                else{
                    String Dest = tfDest.getText() + "#" + "D";
                    req = new RequeteTRAMAP(RequeteTRAMAP.GET_LIST_OP, tfDateDeb.getText(), tfDateFin.getText(), Dest);
                }
                    
            }
            else if(jRadioButton2.isSelected())
            {
                if(jTextFieldIdContainer.getText().equals(""))
                    jLabelAnnoncelist.setText("Il faut remplir les champs");
                else{
                    String Soc = tfSoc.getText() + "#" + "S";
                    req = new RequeteTRAMAP(RequeteTRAMAP.GET_LIST_OP, tfDateDeb.getText(), tfDateFin.getText(), Soc);
                }
           
            }
        }
        try {
            cli.sendRequest(req);//------->
        } catch (IOException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        ReponseTRAMAP rep = null;
        try {
            rep = cli.getResponse();//<------
            if(rep.getCode().equals(ReponseTRAMAP.LIST_OK)){
                booleanVerif = true;
            }
            else{
                booleanVerif = false;
            }
        } catch (IOException ex) {
            Logger.getLogger(DialLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FenAppMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(booleanVerif)
        {
            ArrayList<Integer> al = rep.getAlin();
            for(int i : al)
            {
                dlm.addElement(Integer.toString(i));
            }
            
            jListContainers.setModel(dlm);
            // ur turn
        }
        else
            jLabelAnnoncelist.setText("ERROR LISTING");
        
    }//GEN-LAST:event_jButtonAfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenAppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenAppMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDeco;
    private javax.swing.JButton bDemander;
    private javax.swing.JButton bEnvoyer;
    private javax.swing.JButton bVerifier;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAnnonceIWR;
    private javax.swing.JLabel jLabelAnnoncelist;
    private javax.swing.JLabel jLabelIdContainer;
    private javax.swing.JLabel jLabelIdEmp;
    private javax.swing.JLabel jLabelImma;
    private javax.swing.JLabel jLabelXY;
    private javax.swing.JList jListContainers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldIdContainer;
    private javax.swing.JTextField jTextFieldImma1;
    private javax.swing.JLabel lDeco;
    private javax.swing.JLabel labelAnnonce;
    private javax.swing.JLabel labelContainer;
    private javax.swing.JLabel labelEmplacement;
    private javax.swing.JTextField tfDateDeb;
    private javax.swing.JTextField tfDateFin;
    private javax.swing.JTextField tfDest;
    private javax.swing.JTextField tfNumR;
    private javax.swing.JTextField tfSoc;
    // End of variables declaration//GEN-END:variables
}
